server:
  port: 8080

jwt:
  secret: v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq

spring:
  application:
    name: mini-sns
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_sns
    username: mintuchel
    password: 1234
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.soma.mini_sns.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
