server:
  port: 8080
jwt:
    secret: v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq
spring:
  application:
    name: mini-sns
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_sns
    username: mintuchel
    password: 1234
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    # 기존에 수동으로 만든 테이블이 있어도 Flyway가 관리하기 시작하게 함
    baseline-on-migrate: true
  jpa:
    hibernate:
      # create: 기존 테이블 drop 후 create
      # create-drop: 엔티티와 DB가 일치하는지만 확인
      # update: 엔티티에 필드가 추가되면 DB에도 컬럼을 추가해줍니다. 하지만 기존 컬럼의 삭제나 변경은 반영하지 않는 경우가 많아 주의해야 함.
      # validate: 엔티티와 DB가 일치하는지만 확인. 검사만 하고 직접 고치지 않음 ('Flyway' 쓸때 사용)
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # PostgreSQL의 UUID 생성 등을 위해 Dialect를 명시해주면 더 정확합니다.
        dialect: org.hibernate.dialect.PostgreSQLDialect
